# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a8782c429fd4b695a98afe718ecc7122d44b807d4854cd456e580d24e102ccc11b20c73e47159077253d7abc29d6a888fa3bc0d25fc8a3ca6921a68e07c96ca

test:
  secret_key_base: 0e3874059d8cec8cf4cd34414aacaa68dc63919b9761034a1c35e9f6721b22fa00ec393701bdd372e580163052ee9773450055097fd7dd36c8788418b59a216f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
